优化多级注入器翻译，，这里是通过依赖注入拿到了heroService然后往里更新数据而不是委托给了heroService，，
ng-docs/angular-cn pull request #5
Opened 2022-01-14 07:04 UTC by ganshiqingyuan

优化翻译，，这里是通过依赖注入拿到了heroService然后往里更新数据而不是委托给了heroService，，

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-01-14 09:11 UTC, wszgrcy commented
能提供下对应网页吗?我看看对应的上下文语境

2022-01-14 09:58 UTC, ganshiqingyuan commented
> 能提供下对应网页吗?我看看对应的上下文语境

https://angular.cn/guide/hierarchical-dependency-injection

2022-01-14 10:07 UTC, wszgrcy commented
从设计模式上和语法上,好像都是委托更合适,不过我并非专业人士,召唤 @asnowwolf

2022-01-14 10:35 UTC, ganshiqingyuan commented
> 从设计模式上和语法上,好像都是委托更合适,不过我并非专业人士,召唤 @asnowwolf

``` 它还委托给了全应用级的单例服务 HeroService，它是通过依赖注入机制取得的。``` as a chinese... 谁看谁懵啊，，原英文用的是 ```delegates``` 上一段文档中的这个单词翻译成委托可以理解，，而这一段翻译成委托，，不仅看不懂，，代码里也完全没体现，，代码中只是从全局依赖注入里拿到了```heroService```然后修改他内部的数据从而使依赖于```heroService```数据得其他视图更新而已

2022-01-21 03:15 UTC, asnowwolf commented
委托其实是一个很久以前就流行的词汇了，在 Delphi 时代，就是把事件处理称之为委托。中文编程社区使用委托这个词应该也不少吧，你可以看看 MSDN 的文档，我很久以前用微软系开发的时候经常见到它。
意思是我承担这个职责，但是把这个职责转交给别人去实现，就像工程商的分包一样。你的译法不足以体现这种含义。因为取得只是手段，而非目的。

2022-01-24 02:08 UTC, ganshiqingyuan commented
> 委托其实是一个很久以前就流行的词汇了，在 Delphi 时代，就是把事件处理称之为委托。中文编程社区使用委托这个词应该也不少吧，你可以看看 MSDN 的文档，我很久以前用微软系开发的时候经常见到它。 委托的意思是我承担这个职责，但是把这个职责转交给别人去实现，就像工程商的分包一样。你的译法不足以体现这种含义。因为取得只是手段，而非目的。



这句```委托给了```是谁委托给谁？

2022-01-24 02:48 UTC, asnowwolf commented
委托给服务。也就是说把职责转包给了服务。

2022-01-24 03:27 UTC, ganshiqingyuan commented
> 委托给服务。也就是说把职责转包给了服务。

我说的是那段翻译中的上下文，，谁委托给了谁，和代码中一致不一致

2022-01-24 07:30 UTC, asnowwolf commented
The `HeroTaxReturnService` caches a single `HeroTaxReturn`, tracks changes to that return, and can save or restore it.
It also delegates to the application-wide singleton `HeroService`, which it gets by injection.

`HeroTaxReturnService` 把 "save or restore it" 的职责委托给了 `HeroService`。因为这两个功能并不是 `HeroTaxReturnService` 自己实现的，而是转包给了 `HeroService`。

2022-01-24 09:25 UTC, ganshiqingyuan commented
> The `HeroTaxReturnService` caches a single `HeroTaxReturn`, tracks changes to that return, and can save or restore it. It also delegates to the application-wide singleton `HeroService`, which it gets by injection.
> 
> `HeroTaxReturnService` 把 "save or restore it" 的职责委托给了 `HeroService`。因为这两个功能并不是 `HeroTaxReturnService` 自己实现的，而是转包给了 `HeroService`。

那好，```它还委托给了全应用级的单例服务 HeroService，它是通过依赖注入机制取得的```，，第一个它是指 ```save or restore```，，第二个它是指 ```HeroService``` 就不说这两个它99%的人分不清，，为什么第一个它后面还带个```还```字，，，这可一点也不信雅达

2022-01-24 12:37 UTC, asnowwolf commented
> > The `HeroTaxReturnService` caches a single `HeroTaxReturn`, tracks changes to that return, and can save or restore it. It also delegates to the application-wide singleton `HeroService`, which it gets by injection.
> > `HeroTaxReturnService` 把 "save or restore it" 的职责委托给了 `HeroService`。因为这两个功能并不是 `HeroTaxReturnService` 自己实现的，而是转包给了 `HeroService`。
> 
> 那好，`它还委托给了全应用级的单例服务 HeroService，它是通过依赖注入机制取得的`，，第一个它是指 `save or restore`，，第二个它是指 `HeroService` 就不说这两个它99%的人分不清，，为什么第一个它后面还带个`还`字，，，这可一点也不信雅达

第一个它还是指 HeroTaxReturnService，委托者是它自己，不过它把自己的 save or restore 的职责委托给了 HeroService。如果难以理解，可以改写一下：

报税单服务 `HeroTaxReturnService` 缓存了单条 `HeroTaxReturn`，用于跟踪那个申报单的变更，并且可以保存或还原它。
它把**后两项职责**委托给了全应用级的单例服务 `HeroService`，`HeroService` 是通过依赖注入机制取得的。

你觉得如何？

2022-01-25 02:08 UTC, ganshiqingyuan commented
我觉得可以

2022-01-25 02:37 UTC, asnowwolf requested changes
建议改为：
报税单服务 HeroTaxReturnService 缓存了单条 HeroTaxReturn，用于跟踪那个申报单的变更，并且可以保存或还原它。
它把后两项职责委托给了全应用级的单例服务 HeroService，HeroService 是通过依赖注入机制取得的。

2022-01-25 11:35 UTC, merged